"""criar disciplinas e topicos, vincular sessoes

Revision ID: 0649d297148e
Revises: 4adbb16955ff
Create Date: 2026-07-22 17:57:11.026453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0649d297148e'
down_revision: Union[str, None] = '4adbb16955ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nivel_conhecimento', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_prova_id'), 'disciplinas', ['prova_id'], unique=False)
    op.create_index(op.f('ix_disciplinas_usuario_id'), 'disciplinas', ['usuario_id'], unique=False)
    op.create_table('topicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topicos_disciplina_id'), 'topicos', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_topicos_usuario_id'), 'topicos', ['usuario_id'], unique=False)
    op.add_column('sessoes_estudo', sa.Column('disciplina_id', sa.Integer(), nullable=True))
    op.add_column('sessoes_estudo', sa.Column('topico_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sessoes_estudo_disciplina_id'), 'sessoes_estudo', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_sessoes_estudo_topico_id'), 'sessoes_estudo', ['topico_id'], unique=False)
    op.create_foreign_key(None, 'sessoes_estudo', 'topicos', ['topico_id'], ['id'])
    op.create_foreign_key(None, 'sessoes_estudo', 'disciplinas', ['disciplina_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessoes_estudo', type_='foreignkey')
    op.drop_constraint(None, 'sessoes_estudo', type_='foreignkey')
    op.drop_index(op.f('ix_sessoes_estudo_topico_id'), table_name='sessoes_estudo')
    op.drop_index(op.f('ix_sessoes_estudo_disciplina_id'), table_name='sessoes_estudo')
    op.drop_column('sessoes_estudo', 'topico_id')
    op.drop_column('sessoes_estudo', 'disciplina_id')
    op.drop_index(op.f('ix_topicos_usuario_id'), table_name='topicos')
    op.drop_index(op.f('ix_topicos_disciplina_id'), table_name='topicos')
    op.drop_table('topicos')
    op.drop_index(op.f('ix_disciplinas_usuario_id'), table_name='disciplinas')
    op.drop_index(op.f('ix_disciplinas_prova_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
