"""criar cronograma

Revision ID: 131bc38ad041
Revises: f4d9a41d5740
Create Date: 2026-08-15 16:30:47.010703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131bc38ad041'
down_revision: Union[str, None] = 'f4d9a41d5740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_disciplina_id'), 'cronograma', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_cronograma_usuario_id'), 'cronograma', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cronograma_usuario_id'), table_name='cronograma')
    op.drop_index(op.f('ix_cronograma_disciplina_id'), table_name='cronograma')
    op.drop_table('cronograma')
    # ### end Alembic commands ###
