"""tornar data_prova opcional

Revision ID: 1e6dd1ce329a
Revises: 0649d297148e
Create Date: 2026-07-25 11:36:57.900007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6dd1ce329a'
down_revision: Union[str, None] = '0649d297148e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provas', 'data_prova',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provas', 'data_prova',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
