"""adicionar email_verificado em usuarios

Revision ID: 20d7fdc641cc
Revises: eedf14db65cd
Create Date: 2026-07-27 19:19:22.767187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7fdc641cc'
down_revision: Union[str, None] = 'eedf14db65cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "usuarios",
        sa.Column(
            "email_verificado",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.alter_column(
        "usuarios",
        "email_verificado",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
