"""criar tabela sessoes_estudo

Revision ID: 26dc9e39b3d0
Revises: ecdb0abfc348
Create Date: 2026-07-16 23:23:32.939371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26dc9e39b3d0'
down_revision: Union[str, None] = 'ecdb0abfc348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('objetivo', sa.String(length=500), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('concentracao', sa.Integer(), nullable=True),
    sa.Column('dificuldade', sa.Integer(), nullable=True),
    sa.Column('aprendizado_percentual', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_estudo_prova_id'), 'sessoes_estudo', ['prova_id'], unique=False)
    op.create_index(op.f('ix_sessoes_estudo_usuario_id'), 'sessoes_estudo', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_estudo_usuario_id'), table_name='sessoes_estudo')
    op.drop_index(op.f('ix_sessoes_estudo_prova_id'), table_name='sessoes_estudo')
    op.drop_table('sessoes_estudo')
    # ### end Alembic commands ###
