"""criar tabelas provas e usuarios

Revision ID: 2e1a292ae9a2
Revises: 
Create Date: 2026-07-16 00:42:19.267251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1a292ae9a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ENEM', 'VESTIBULAR', 'CONCURSO', name='tipoprova'), nullable=False),
    sa.Column('instituicao_banca', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('data_prova', sa.Date(), nullable=False),
    sa.Column('data_divulgacao_edital', sa.Date(), nullable=True),
    sa.Column('horas_disponiveis_dia', sa.Float(), nullable=False),
    sa.Column('dias_disponiveis_semana', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='prioridadeprova'), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'CONCLUIDA', 'ARQUIVADA', name='statusprova'), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('provas')
    # ### end Alembic commands ###
