"""adicionar email_verificado em usuarios

Revision ID: 34321f85383a
Revises: 20d7fdc641cc
Create Date: 2026-07-28 13:57:50.320567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34321f85383a'
down_revision: Union[str, None] = '20d7fdc641cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "usuarios",
        sa.Column(
            "eh_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # Remove o DEFAULT do banco após preencher os registros existentes
    op.alter_column(
        "usuarios",
        "eh_admin",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'eh_admin')
    # ### end Alembic commands ###
