"""criar tabela revisoes

Revision ID: 4adbb16955ff
Revises: 26dc9e39b3d0
Create Date: 2026-07-17 22:29:37.353903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4adbb16955ff'
down_revision: Union[str, None] = '26dc9e39b3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('sessao_estudo_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('intervalo_numero', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['sessao_estudo_id'], ['sessoes_estudo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisoes_data_agendada'), 'revisoes', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_revisoes_prova_id'), 'revisoes', ['prova_id'], unique=False)
    op.create_index(op.f('ix_revisoes_sessao_estudo_id'), 'revisoes', ['sessao_estudo_id'], unique=False)
    op.create_index(op.f('ix_revisoes_usuario_id'), 'revisoes', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisoes_usuario_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_sessao_estudo_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_prova_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_data_agendada'), table_name='revisoes')
    op.drop_table('revisoes')
    # ### end Alembic commands ###
