"""add_cascade_to_topico_relations

Revision ID: 8f263324e666
Revises: 131bc38ad041
Create Date: 2026-08-15 17:42:38.250060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f263324e666'
down_revision: Union[str, None] = '131bc38ad041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anotacoes_topico_id_fkey', 'anotacoes', type_='foreignkey')
    op.drop_constraint('anotacoes_usuario_id_fkey', 'anotacoes', type_='foreignkey')
    op.create_foreign_key(None, 'anotacoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'anotacoes', 'topicos', ['topico_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('revisoes_prova_id_fkey', 'revisoes', type_='foreignkey')
    op.drop_constraint('revisoes_usuario_id_fkey', 'revisoes', type_='foreignkey')
    op.drop_constraint('revisoes_topico_id_fkey', 'revisoes', type_='foreignkey')
    op.drop_constraint('revisoes_sessao_estudo_id_fkey', 'revisoes', type_='foreignkey')
    op.create_foreign_key(None, 'revisoes', 'topicos', ['topico_id'], ['id'])
    op.create_foreign_key(None, 'revisoes', 'sessoes_estudo', ['sessao_estudo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'revisoes', 'provas', ['prova_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'revisoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sessoes_estudo_topico_id_fkey', 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key(None, 'sessoes_estudo', 'topicos', ['topico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key('sessoes_estudo_topico_id_fkey', 'sessoes_estudo', 'topicos', ['topico_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.create_foreign_key('revisoes_sessao_estudo_id_fkey', 'revisoes', 'sessoes_estudo', ['sessao_estudo_id'], ['id'])
    op.create_foreign_key('revisoes_topico_id_fkey', 'revisoes', 'topicos', ['topico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('revisoes_usuario_id_fkey', 'revisoes', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('revisoes_prova_id_fkey', 'revisoes', 'provas', ['prova_id'], ['id'])
    op.drop_constraint(None, 'anotacoes', type_='foreignkey')
    op.drop_constraint(None, 'anotacoes', type_='foreignkey')
    op.create_foreign_key('anotacoes_usuario_id_fkey', 'anotacoes', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('anotacoes_topico_id_fkey', 'anotacoes', 'topicos', ['topico_id'], ['id'])
    # ### end Alembic commands ###
