"""criar assinaturas e pagamentos

Revision ID: 9068cd71922d
Revises: a4b75c471f5d
Create Date: 2026-08-06 13:23:33.727666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9068cd71922d'
down_revision: Union[str, None] = 'a4b75c471f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plano', sa.Enum('MENSAL', 'ANUAL', name='plano'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVA', 'CANCELADA', 'EXPIRADA', name='statusassinatura'), nullable=False),
    sa.Column('mercadopago_preapproval_id', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_mercadopago_preapproval_id'), 'assinaturas', ['mercadopago_preapproval_id'], unique=False)
    op.create_index(op.f('ix_assinaturas_usuario_id'), 'assinaturas', ['usuario_id'], unique=True)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('mercadopago_payment_id', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_assinatura_id'), 'pagamentos', ['assinatura_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_mercadopago_payment_id'), 'pagamentos', ['mercadopago_payment_id'], unique=True)
    op.drop_constraint('anotacoes_usuario_id_fkey', 'anotacoes', type_='foreignkey')
    op.create_foreign_key(None, 'anotacoes', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('disciplinas_usuario_id_fkey', 'disciplinas', type_='foreignkey')
    op.create_foreign_key(None, 'disciplinas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('eventos_metrica_usuario_id_fkey', 'eventos_metrica', type_='foreignkey')
    op.create_foreign_key(None, 'eventos_metrica', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('provas_usuario_id_fkey', 'provas', type_='foreignkey')
    op.create_foreign_key(None, 'provas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('revisoes_usuario_id_fkey', 'revisoes', type_='foreignkey')
    op.create_foreign_key(None, 'revisoes', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('sessoes_estudo_usuario_id_fkey', 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key(None, 'sessoes_estudo', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('topicos_usuario_id_fkey', 'topicos', type_='foreignkey')
    op.create_foreign_key(None, 'topicos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topicos', type_='foreignkey')
    op.create_foreign_key('topicos_usuario_id_fkey', 'topicos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key('sessoes_estudo_usuario_id_fkey', 'sessoes_estudo', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.create_foreign_key('revisoes_usuario_id_fkey', 'revisoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'provas', type_='foreignkey')
    op.create_foreign_key('provas_usuario_id_fkey', 'provas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'eventos_metrica', type_='foreignkey')
    op.create_foreign_key('eventos_metrica_usuario_id_fkey', 'eventos_metrica', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'disciplinas', type_='foreignkey')
    op.create_foreign_key('disciplinas_usuario_id_fkey', 'disciplinas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'anotacoes', type_='foreignkey')
    op.create_foreign_key('anotacoes_usuario_id_fkey', 'anotacoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pagamentos_mercadopago_payment_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_assinatura_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_assinaturas_usuario_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_mercadopago_preapproval_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    # ### end Alembic commands ###
