"""criar eventos_metrica, adicionar eh_admin em usuarios

Revision ID: a4b75c471f5d
Revises: eab9815e4ebf
Create Date: 2026-07-28 15:35:38.604692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b75c471f5d'
down_revision: Union[str, None] = 'eab9815e4ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
