"""initial migration

Revision ID: b9a5fcb2555d
Revises: 
Create Date: 2026-09-11 10:24:52.362954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a5fcb2555d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('eh_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plano', sa.Enum('MENSAL', 'ANUAL', name='plano'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVA', 'CANCELADA', 'EXPIRADA', name='statusassinatura'), nullable=False),
    sa.Column('mercadopago_preapproval_id', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_mercadopago_preapproval_id'), 'assinaturas', ['mercadopago_preapproval_id'], unique=False)
    op.create_index(op.f('ix_assinaturas_usuario_id'), 'assinaturas', ['usuario_id'], unique=True)
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('EVENTO', 'TAREFA', name='tipoevento'), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_calendario_data'), 'eventos_calendario', ['data'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_usuario_id'), 'eventos_calendario', ['usuario_id'], unique=False)
    op.create_table('eventos_metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_metrica_criado_em'), 'eventos_metrica', ['criado_em'], unique=False)
    op.create_index(op.f('ix_eventos_metrica_tipo_evento'), 'eventos_metrica', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_eventos_metrica_usuario_id'), 'eventos_metrica', ['usuario_id'], unique=False)
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ENEM', 'VESTIBULAR', 'CONCURSO', name='tipoprova'), nullable=False),
    sa.Column('instituicao_banca', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('data_prova', sa.Date(), nullable=True),
    sa.Column('data_divulgacao_edital', sa.Date(), nullable=True),
    sa.Column('horas_disponiveis_dia', sa.Float(), nullable=False),
    sa.Column('dias_disponiveis_semana', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='prioridadeprova'), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'CONCLUIDA', 'ARQUIVADA', name='statusprova'), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provas_usuario_id'), 'provas', ['usuario_id'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nivel_conhecimento', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_prova_id'), 'disciplinas', ['prova_id'], unique=False)
    op.create_index(op.f('ix_disciplinas_usuario_id'), 'disciplinas', ['usuario_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('mercadopago_payment_id', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_assinatura_id'), 'pagamentos', ['assinatura_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_mercadopago_payment_id'), 'pagamentos', ['mercadopago_payment_id'], unique=True)
    op.create_table('cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_disciplina_id'), 'cronograma', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_cronograma_usuario_id'), 'cronograma', ['usuario_id'], unique=False)
    op.create_table('topicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topicos_disciplina_id'), 'topicos', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_topicos_usuario_id'), 'topicos', ['usuario_id'], unique=False)
    op.create_table('anotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anotacoes_topico_id'), 'anotacoes', ['topico_id'], unique=True)
    op.create_index(op.f('ix_anotacoes_usuario_id'), 'anotacoes', ['usuario_id'], unique=False)
    op.create_table('materiais_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_estudo_criado_em'), 'materiais_estudo', ['criado_em'], unique=False)
    op.create_index(op.f('ix_materiais_estudo_usuario_id'), 'materiais_estudo', ['usuario_id'], unique=False)
    op.create_table('sessoes_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('objetivo', sa.String(length=500), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('concentracao', sa.Integer(), nullable=True),
    sa.Column('dificuldade', sa.Integer(), nullable=True),
    sa.Column('aprendizado_percentual', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_estudo_disciplina_id'), 'sessoes_estudo', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_sessoes_estudo_prova_id'), 'sessoes_estudo', ['prova_id'], unique=False)
    op.create_index(op.f('ix_sessoes_estudo_topico_id'), 'sessoes_estudo', ['topico_id'], unique=False)
    op.create_index(op.f('ix_sessoes_estudo_usuario_id'), 'sessoes_estudo', ['usuario_id'], unique=False)
    op.create_table('avaliacoes_desempenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('total_questoes', sa.Integer(), nullable=False),
    sa.Column('total_acertos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais_estudo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_desempenho_usuario_id'), 'avaliacoes_desempenho', ['usuario_id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('alternativas', sa.JSON(), nullable=False),
    sa.Column('resposta_correta', sa.String(length=1), nullable=False),
    sa.Column('explicacao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais_estudo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_material_id'), 'questoes', ['material_id'], unique=False)
    op.create_table('revisoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('sessao_estudo_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('intervalo_numero', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessao_estudo_id'], ['sessoes_estudo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisoes_data_agendada'), 'revisoes', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_revisoes_prova_id'), 'revisoes', ['prova_id'], unique=False)
    op.create_index(op.f('ix_revisoes_sessao_estudo_id'), 'revisoes', ['sessao_estudo_id'], unique=False)
    op.create_index(op.f('ix_revisoes_topico_id'), 'revisoes', ['topico_id'], unique=False)
    op.create_index(op.f('ix_revisoes_usuario_id'), 'revisoes', ['usuario_id'], unique=False)
    op.create_table('historico_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('alternativa_selecionada', sa.String(length=1), nullable=False),
    sa.Column('acertou', sa.Boolean(), nullable=False),
    sa.Column('respondido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_respostas_questao_id'), 'historico_respostas', ['questao_id'], unique=False)
    op.create_index(op.f('ix_historico_respostas_usuario_id'), 'historico_respostas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_respostas_usuario_id'), table_name='historico_respostas')
    op.drop_index(op.f('ix_historico_respostas_questao_id'), table_name='historico_respostas')
    op.drop_table('historico_respostas')
    op.drop_index(op.f('ix_revisoes_usuario_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_topico_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_sessao_estudo_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_prova_id'), table_name='revisoes')
    op.drop_index(op.f('ix_revisoes_data_agendada'), table_name='revisoes')
    op.drop_table('revisoes')
    op.drop_index(op.f('ix_questoes_material_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_avaliacoes_desempenho_usuario_id'), table_name='avaliacoes_desempenho')
    op.drop_table('avaliacoes_desempenho')
    op.drop_index(op.f('ix_sessoes_estudo_usuario_id'), table_name='sessoes_estudo')
    op.drop_index(op.f('ix_sessoes_estudo_topico_id'), table_name='sessoes_estudo')
    op.drop_index(op.f('ix_sessoes_estudo_prova_id'), table_name='sessoes_estudo')
    op.drop_index(op.f('ix_sessoes_estudo_disciplina_id'), table_name='sessoes_estudo')
    op.drop_table('sessoes_estudo')
    op.drop_index(op.f('ix_materiais_estudo_usuario_id'), table_name='materiais_estudo')
    op.drop_index(op.f('ix_materiais_estudo_criado_em'), table_name='materiais_estudo')
    op.drop_table('materiais_estudo')
    op.drop_index(op.f('ix_anotacoes_usuario_id'), table_name='anotacoes')
    op.drop_index(op.f('ix_anotacoes_topico_id'), table_name='anotacoes')
    op.drop_table('anotacoes')
    op.drop_index(op.f('ix_topicos_usuario_id'), table_name='topicos')
    op.drop_index(op.f('ix_topicos_disciplina_id'), table_name='topicos')
    op.drop_table('topicos')
    op.drop_index(op.f('ix_cronograma_usuario_id'), table_name='cronograma')
    op.drop_index(op.f('ix_cronograma_disciplina_id'), table_name='cronograma')
    op.drop_table('cronograma')
    op.drop_index(op.f('ix_pagamentos_mercadopago_payment_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_assinatura_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_disciplinas_usuario_id'), table_name='disciplinas')
    op.drop_index(op.f('ix_disciplinas_prova_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_provas_usuario_id'), table_name='provas')
    op.drop_table('provas')
    op.drop_index(op.f('ix_eventos_metrica_usuario_id'), table_name='eventos_metrica')
    op.drop_index(op.f('ix_eventos_metrica_tipo_evento'), table_name='eventos_metrica')
    op.drop_index(op.f('ix_eventos_metrica_criado_em'), table_name='eventos_metrica')
    op.drop_table('eventos_metrica')
    op.drop_index(op.f('ix_eventos_calendario_usuario_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_data'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    op.drop_index(op.f('ix_assinaturas_usuario_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_mercadopago_preapproval_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
