"""criar anotacoes, adicionar topico_id em revisoes

Revision ID: cfc1c1ab6be4
Revises: 1e6dd1ce329a
Create Date: 2026-07-26 17:41:30.419489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc1c1ab6be4'
down_revision: Union[str, None] = '1e6dd1ce329a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisoes', sa.Column('topico_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_revisoes_topico_id'), 'revisoes', ['topico_id'], unique=False)
    op.create_foreign_key(None, 'revisoes', 'topicos', ['topico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.drop_index(op.f('ix_revisoes_topico_id'), table_name='revisoes')
    op.drop_column('revisoes', 'topico_id')
    # ### end Alembic commands ###
