"""criar tabela eventos_metrica

Revision ID: eab9815e4ebf
Revises: 34321f85383a
Create Date: 2026-07-28 15:26:27.252597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab9815e4ebf'
down_revision: Union[str, None] = '34321f85383a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_metrica_criado_em'), 'eventos_metrica', ['criado_em'], unique=False)
    op.create_index(op.f('ix_eventos_metrica_tipo_evento'), 'eventos_metrica', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_eventos_metrica_usuario_id'), 'eventos_metrica', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_metrica_usuario_id'), table_name='eventos_metrica')
    op.drop_index(op.f('ix_eventos_metrica_tipo_evento'), table_name='eventos_metrica')
    op.drop_index(op.f('ix_eventos_metrica_criado_em'), table_name='eventos_metrica')
    op.drop_table('eventos_metrica')
    # ### end Alembic commands ###
