"""adicionar usuario_id em provas

Revision ID: ecdb0abfc348
Revises: 2e1a292ae9a2
Create Date: 2026-07-16 18:44:25.495257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdb0abfc348'
down_revision: Union[str, None] = '2e1a292ae9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_provas_usuario_id'), 'provas', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'provas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provas', type_='foreignkey')
    op.drop_index(op.f('ix_provas_usuario_id'), table_name='provas')
    op.drop_column('provas', 'usuario_id')
    # ### end Alembic commands ###
