"""criar tabela de anotacoes

Revision ID: eedf14db65cd
Revises: cfc1c1ab6be4
Create Date: 2026-07-26 19:17:30.690527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedf14db65cd'
down_revision: Union[str, None] = 'cfc1c1ab6be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anotacoes_topico_id'), 'anotacoes', ['topico_id'], unique=True)
    op.create_index(op.f('ix_anotacoes_usuario_id'), 'anotacoes', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anotacoes_usuario_id'), table_name='anotacoes')
    op.drop_index(op.f('ix_anotacoes_topico_id'), table_name='anotacoes')
    op.drop_table('anotacoes')
    # ### end Alembic commands ###
