"""criar eventos_calendario

Revision ID: f4d9a41d5740
Revises: 9068cd71922d
Create Date: 2026-08-12 20:39:04.714857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d9a41d5740'
down_revision: Union[str, None] = '9068cd71922d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('EVENTO', 'TAREFA', name='tipoevento'), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_calendario_data'), 'eventos_calendario', ['data'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_usuario_id'), 'eventos_calendario', ['usuario_id'], unique=False)
    op.drop_constraint('disciplinas_usuario_id_fkey', 'disciplinas', type_='foreignkey')
    op.create_foreign_key(None, 'disciplinas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('eventos_metrica_usuario_id_fkey', 'eventos_metrica', type_='foreignkey')
    op.create_foreign_key(None, 'eventos_metrica', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('provas_usuario_id_fkey', 'provas', type_='foreignkey')
    op.create_foreign_key(None, 'provas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('revisoes_usuario_id_fkey', 'revisoes', type_='foreignkey')
    op.create_foreign_key(None, 'revisoes', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('sessoes_estudo_usuario_id_fkey', 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key(None, 'sessoes_estudo', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('topicos_usuario_id_fkey', 'topicos', type_='foreignkey')
    op.create_foreign_key(None, 'topicos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topicos', type_='foreignkey')
    op.create_foreign_key('topicos_usuario_id_fkey', 'topicos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessoes_estudo', type_='foreignkey')
    op.create_foreign_key('sessoes_estudo_usuario_id_fkey', 'sessoes_estudo', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'revisoes', type_='foreignkey')
    op.create_foreign_key('revisoes_usuario_id_fkey', 'revisoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'provas', type_='foreignkey')
    op.create_foreign_key('provas_usuario_id_fkey', 'provas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'eventos_metrica', type_='foreignkey')
    op.create_foreign_key('eventos_metrica_usuario_id_fkey', 'eventos_metrica', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'disciplinas', type_='foreignkey')
    op.create_foreign_key('disciplinas_usuario_id_fkey', 'disciplinas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_eventos_calendario_usuario_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_data'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    # ### end Alembic commands ###
